app/src/example-data.js, packages/ckeditor5-coremedia-richtext/src/CoreMediaRichTextConfig.ts, packages/ckeditor5-coremedia-richtext/src/RichTextDataProcessor.ts, packages/ckeditor5-dataprocessor-support/__tests__/TextProxy.test.ts, packages/ckeditor5-dataprocessor-support/src/TextProxy.ts
As described in #39, the previous implementation caused `&lt;` and `&gt;` to be processed to `<` and `>` directly before writing CoreMedia RichText 1.0 Data back to the server. This, for example, caused `Lorem&lt;elem&gt;Ipsum` to be stored as `LoremIpsum`.
The fix is, to remove trying to decode entities in `toData` processing. Once required in CKEditor 4 integration for CoreMedia CMS, it does not match CKEditor 5 behavior nowadays, which is, that entities are always handed over to `toData` processing as resolved UTF-8 characters, rather than raw entities.
* #35 needs to be merged prior to this, as the changes base on the changes made on that branch
=> fix(#39): Fixes Corrupted XML Entities in CoreMedia RichText Data

app/src/example-data.js, packages/ckeditor5-coremedia-richtext/src/RichTextDataProcessor.ts
Just as an empty text in data view is transformed to an empty string, we should accept the same string as input to `toView`. Before that, it was required to always pass a valid RichText document (here: representing an empty state).
Now, we skip XML parsing and directly set the empty data. This much more matches the general approach of clearing an editor by setting its data to an empty string.
=> fix(data-processor): Should accept `setData("")`

.github/workflows/feature-branches.yml, .github/workflows/release.yml
Until now our packages are published to the npm repository with tag "latest".
This means customer get the suggestion to update there package to the "latest" versions.
We have to prevent this for prereleases (pull requests and rc builds) so customers do not accidentially update to a prerelease.
Pullrequest builds will now get the tag "pullrequest", rc "next" and releases will stay "latest".
=> Prevent usage of release version tag "latest" for prerelease builds

.github/workflows/package-listing.yml, .github/workflows/unpublish.yml
Improves the maintenance of prerelease versions.
To find out which versions for which package with the scope @coremedia/ckeditor5 is currently deployed a new workflow has been introduced. This workflow can be used to determine which versions have to be unpublished.
The unpublishing workflow has been improved by trying to unpublish a given version for each @coremedia/ckeditor5 package which exist. As it doesn't matter if the version to unpublish exist this is totally valid.
=> CI: Improve unpublish and provide a listing of all packages with versions.

.github/workflows/package-listing.yml, types/ckeditor__ckeditor5-editor-classic/package.json
Earlier on a package listing and unpublish has been introduced for the coremedia/ckeditor packages but not for the types.
=> CI: Add types to the housekeeping

.github/workflows/codeql-analysis.yml, app/src/example-data.js
Adds [CodeQL](https://codeql.github.com/docs/codeql-overview/) scanning as GitHub Action.
False-Positive matches and similar can be suppressed in JavaScript/TypeScript files like:
```
function same(x, y)  {
if (x !== x && y !== y)  // lgtm[js/comparison-of-identical-expressions]
return true;
return x === y;
}
```
(see [Alert suppression - Help - LGTM](https://lgtm.com/help/lgtm/alert-suppression#javascript))
=> Adding GitHub Action for CodeQL scanning

.github/workflows/pre-release.yml, .github/workflows/release.yml, package.json, packages/ckeditor5-coremedia-richtext/__tests__/DataDrivenTests.ts, packages/ckeditor5-coremedia-richtext/__tests__/ToDataProcessor.test.ts, packages/ckeditor5-dataprocessor-support/__tests__/ElementProxy.test.ts, packages/ckeditor5-dataprocessor-support/__tests__/HtmlFilter.test.ts, packages/ckeditor5-dataprocessor-support/__tests__/Rules.test.ts, packages/ckeditor5-dataprocessor-support/__tests__/TextProxy.test.ts, packages/ckeditor5-font-mapper/src/FontMappingRegistry.ts, pnpm-lock.yaml, typedoc-tsconfig.json, typedoc.json
This PR fixes TypeDoc in this repository.
It also adds a TypeDoc step to the release and pre-release github workflows.
TypeDoc was broken for several reasons:
- Missing path dependencies for new packages in the typedoc-tsconfig
- TS Issues in the itest package (got excluded)
- Some minor TS issues which did not prevent building the packages, but resulted in TypeDoc Errors
=> Fix: Reenable Typedoc

packages/ckeditor5-coremedia-link/src/contentlink/ui/ContentLinkActionsViewExtension.ts, packages/ckeditor5-coremedia-link/src/linktarget/LinkTarget.ts
This PR fixes 2 issues with content links:
1. Switching between external and internal links now works properly.
Before, there was an issue while opening a link balloon containing content links and external links.
The balloon would not update correctly if an external link was displayed after showing a content link.
2. Clicking on a content link now closes the contextual balloon.
The previous behavior caused an issue in CoreMedia Studio. The balloon would not lose focus, but clicking on the
link triggers another content tab to open. Since the balloon is not part of the editor's DOM tree, it would then still be visible.
=> Fix: Content Link Issues

.github/workflows/pre-release-gc.yml
Introduces GitHub Action _"GC Pre-Releases"_.
It is meant to replace actions such as _"Unpublish Versions"_ and possibly even _"List Packages"_.
The job will automatically delete old pre-release versions.
It comes with a double safety-net:
* By default, it retains **all** pre-release versions.
* By default, the action is run in **dry-run** mode.
Regarding "retain" decided to stick to a simple set of:
- **all (default):** Keep all pre-release versions
- **none:** Remove all pre-release versions
- **last:** Only keep last pre-release version.
=> GitHub Actions: Half-Automatic Garbage Collection of Pre-Release Versions

app/sample/styles.css, itest/src/Differencing.test.ts, packages/ckeditor5-coremedia-differencing/src/Differencing.ts, packages/ckeditor5-coremedia-differencing/src/Xdiff.ts, packages/ckeditor5-coremedia-example-data/src/data/DifferencingData.ts, packages/ckeditor5-coremedia-richtext/src/CoreMediaRichTextConfig.ts, packages/ckeditor5-coremedia-richtext/src/RichTextDataProcessor.ts
To fix the issue of false-positive newline highlighting in context of server-side differencing, we have essentially provided one important difference:
We introduced a new artificial `xdiff:br` element, available in data view and especially in editing view. Having this, previous styling has to be adapted for newline highlighting.
* CSS Selector Before: `p > xdiff\:span[xdiff\:class="diff-html-added"]:empty::before`
* CSS Selector Now: `p > xdiff\:br[xdiff\:class="diff-html-added"]::before`
You could still use `:empty` pseudo-class, but it is not required anymore, as `xdiff:br` is always empty.
Further changes, not directly visible, ensure, that differences with whitespace is better handled and whitespace not stripped by CKEditor's processing.
CoreMedia's server side differencing challenges …
=> Differencing: Get Rid of False-Positive Newline Added

app/sample/index.html, app/src/ckeditor.js, app/src/readOnlySupport.js, packages/ckeditor5-core-common/src/Commands.ts, packages/ckeditor5-coremedia-link/src/linktarget/LinkTargetActionsViewExtension.ts, packages/ckeditor5-coremedia-link/src/linktarget/ui/CustomLinkTargetInputFormView.ts, packages/ckeditor5-coremedia-link/src/linktarget/ui/CustomLinkTargetUI.ts
The link-target feature ignored the read-only state of the editor:
This PR applies the following fixes:
* **Buttons in Actions View are Disabled**
* **Save Button in Form View is Disabled**
* Disabled State:
* Enabled State:
This is the same behavior as for CKEditor 5 Link Feature, when editing a link URL, while the editor becomes disabled. Thus, only the Save button becomes disabled, while the input field as well as the cancel button stay enabled.
The example application now has a read-only toggle button, similar to the example as provided by [CKEditor 5](https://ckeditor.com/docs/ckeditor5/35.0.1/features/read-only.html):
As can be seen in the screenshot, a click accepts modifier keys to trigger state switch after a given timeout:
* Ctrl/Cmd+Click: 10 seconds delay
* Shift+Click: 60 …
=> Link-Target Feature: Respect Read-Only State of Editor

app/src/example-data.js, packages/ckeditor5-coremedia-example-data/src/RichTextBase.ts, packages/ckeditor5-coremedia-example-data/src/RichTextDOM.ts, packages/ckeditor5-coremedia-example-data/src/data/LinkTargetData.ts
For Playwright tests, we don't have jsdom at hand, and thus, we cannot create a DOMParser instance.
Moved corresponding code to extra file `RichTextDOM` which can now be used by tests or for example-data creation where JSDOM is available.
=> fix(playwright): No DOMParser available

.eslintrc.json, packages/ckeditor5-coremedia-link/__tests__/linktarget/config/DefaultTarget.test.ts, packages/ckeditor5-coremedia-richtext/__tests__/ToDataProcessor.test.ts, packages/ckeditor5-dataprocessor-support/__tests__/ElementProxy.test.ts
Fixes ESLint Warnings:
* `@typescript-eslint/no-unused-vars`
* `@typescript-eslint/no-non-null-assertion`
Raising them to error level, so that we don't miss them.
Also added:
* `@typescript-eslint/prefer-ts-expect-error`
and fixed the only issue. We prefer `ts-expect-error` so that we are aware, when the corresponding type got fixed.
=> Fixes ESLint Warnings and Raises them to Errors

packages/ckeditor5-core-common/package.json, packages/ckeditor5-coremedia-content-clipboard/package.json, packages/ckeditor5-coremedia-differencing/package.json, packages/ckeditor5-coremedia-images/package.json, packages/ckeditor5-coremedia-link/package.json, packages/ckeditor5-coremedia-richtext-support/package.json, packages/ckeditor5-coremedia-richtext/package.json, packages/ckeditor5-coremedia-studio-essentials/package.json, packages/ckeditor5-coremedia-studio-integration-mock/package.json, packages/ckeditor5-dataprocessor-support/package.json, packages/ckeditor5-font-mapper/package.json
This is a follow up of https://github.com/CoreMedia/ckeditor-plugins/pull/94. 
Unfortunately, update-latest didn't update the versions in peer dependencies.
=> CKEditor 5 Update in peer dependencies

README.md, app/package.json, app/src/ckeditor.js, packages/ckeditor5-coremedia-studio-essentials/package.json, pnpm-lock.yaml
The package `@coremedia/ckeditor5-studio-essentials` has been renamed to `@coremedia/ckeditor-coremedia-studio-essentials`.
This is a breaking change and requires some action when upgrading to upcoming major version:
- Dependencies to this package have to be changed to the new name.
- All imports in *.ts files have to been changed to the new name.
=> Studio Essentials: Adapt package name to directory name to fit naming policy.

packages/ckeditor5-coremedia-richtext/README.md, packages/ckeditor5-coremedia-richtext/__tests__/DataDrivenTests.ts, packages/ckeditor5-coremedia-richtext/__tests__/rules/Heading.test.ts, packages/ckeditor5-coremedia-richtext/__tests__/rules/Inline.test.ts, packages/ckeditor5-coremedia-richtext/src/rules/Heading.ts, packages/ckeditor5-coremedia-richtext/src/rules/ReplaceBy.ts, packages/ckeditor5-dataprocessor-support/src/Attributes.ts, packages/ckeditor5-dataprocessor-support/src/RulesLogger.ts, packages/ckeditor5-dataprocessor-support/src/index-doc.ts
This PR documents ambiguous class mapping behavior, provides corresponding tests and raises warnings if ambiguous states in data are detected.
As described in #101 class mappings may be ambiguous:
```html
<span class="underline strike">Lorem</span>
```
This ambiguity is triggered by so-called _reserved classes_, i.e., class attribute values in CoreMedia RichText 1.0, which denote a `<span>` to be mapped to a different representation in data view (such as `<u>` or `<s>` in the example above).
While we could decide to map such a state to:
```html
<u><s>Lorem</s></u>
```
such a decision would raise additional issues like:
* The data-processed example later retrieved by `getData()` would differ:
```html
<span class="underline"><span class="strike">Lorem</span></span>
```
* Where to apply …
=> Fixes #101: Address Ambiguous Class Mappings By Warnings and Documentation

app/sample/styles.css
Given an image, which is embedded into a link, the link balloon (action view/form view) may have opened misplaced for aligned images (`float--left`, `float--right`).
This pull request addresses this by applying the same alignment to the surrounding anchor tag.
Solution uses the `:has` CSS pseudo-class. Please see [caniuse.com](https://caniuse.com/css-has) browser support and thus possible limitations, if the fix will work in your browser.
A similar fix has to be provided for CoreMedia Studio.
=> Example App: Fix link balloon position when set on image.

itest/src/DocumentLists.test.ts, itest/src/aut/ApplicationWrapper.ts, packages/ckeditor5-coremedia-example-data/src/RichTextBase.ts
Provide tests for document list integration with possible valid CoreMedia RichText 1.0 structures.
It is important, that no relevant information is lost for any valid CoreMedia RichText read from server.
While testing, we detected one issue, we rate minor for now:
```xml
<ul>
<li><p>Text</p></li>
</ul>
```
gets the extra paragraph stripped off:
```xml
<ul>
<li>Text</li>
</ul>
```
The paragraph is not stripped by CKEditor, when it contains additional attributes such as:
```xml
<ul>
<li><p class="some--class">Text</p></li>
</ul>
```
The tests are meant to provide confidence, that on CKEditor updates, contracts we rely on are still valid.
=> Tests for lists

app/src/ckeditor.ts, app/src/dragExamples.ts, itest/src/DragDrop.test.ts, itest/src/aut/ApplicationWrapper.ts, itest/src/aut/MockDragDropPluginWrapper.ts, packages/ckeditor5-coremedia-example-data/src/tsconfig.json, packages/ckeditor5-coremedia-studio-integration-mock/src/content/MockDragDropPlugin.ts
Provides a bunch of tests for dragging and dropping contents directly into the editing view of CKEditor.
Introduces `MockDragDropPlugin` as extension to example application, to easily create draggable examples right from the tests. These draggable examples mock other drag and drop sources like the library in CoreMedia Studio.
=> Tests: Drag & Drop

packages/ckeditor5-font-mapper/src/FontMapping.ts
The versions can be compared by executing the following code snippets in the developer console.
Old version:
````
document.createElement("div").innerHTML = '<img src="nonexistent_image" onerror="alert(1337)">'
````
Result in Chrome: 
> 118:1 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src github.githubassets.com". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
New version:
````
document.createElement("textarea").innerHTML = '<img src="nonexistent_image" onerror="alert(1337)">'
````
Result in Chrome:
> …
=> Security: Change the way how to decode HTML Entities.

packages/ckeditor5-coremedia-content-clipboard/src/ContentMarkers.ts
When something is selected in the editor and the paste button is used the selected content has to be removed before inserting.
=> Paste Button: Handle expanded ranges

VERSIONING.md
We came to the conclusion, that for security issues we may require a different policy to keep compatibility with related CMCC releases at best effort. The new VERSIONING.md incorporates these recent decisions.
=> docs: Update VERSIONING.md

packages/ckeditor5-coremedia-richtext/src/CoreMediaRichTextConfig.ts, packages/ckeditor5-coremedia-richtext/src/RichTextDataProcessor.ts
Fixes exception when no rules got specified in configuration:
```
RichTextDataProcessor: Uncaught (in promise) TypeError: _config.rules is not iterable
```
And, to be able to detect such issues, marked `rules` in `LatestCoreMediaRichTextConfig` as optional  (which is the same as for `V10CoreMediaRichTextConfig`).
=> fix(data-processor): Fixes TypeError "is not iterable"

packages/ckeditor5-coremedia-richtext/src/RichTextDataProcessor.ts, packages/ckeditor5-dom-converter/src/RuleBasedConversionListener.ts
Recent refactoring of rule based processing introduced a bug, that prevented enabling ckdebug mode.
Switching to explicit `Logger` reference instead of trying to pass just some method-handles.
=> fix(data-processor): Fixes isDebugEnabled on undefined

packages/ckeditor5-dom-converter/src/HtmlDomConverter.ts
"imported" output wrongly outputs the incoming node as result, but it is the resulting node, which needs to be logged instead.
=> fix(data-processor): Fixes Debugging Output

itest/src/Images.test.ts, packages/ckeditor5-coremedia-images/src/ContentImageEditingPlugin.ts, packages/ckeditor5-coremedia-images/src/converters.ts
We cannot assume that processed images have a valid uriPath as xlink-href. In case the attribute is not a valid uriPath, we must exit early, to not run into an error which would break the editor.
We Therefore must check if the attribute is set on downcast, right before creating the spinner marker. If the xlink-href is empty (empty string), simply show a broken image. (Skip the rest of the computation)
Later, the xlink-href attribute is converted to the resulting uriPath. If this fails, do not break the editor, but instead just return early. In this case, the spinner will stay.
=> fix(images): Catch unwanted xlink-href attributes

packages/ckeditor5-coremedia-link/src/contentlink/ContentLinks.ts, packages/ckeditor5-coremedia-link/src/contentlink/ui/ContentLinkActionsViewExtension.ts, packages/ckeditor5-coremedia-link/src/contentlink/ui/ContentLinkFormViewExtension.ts, packages/ckeditor5-coremedia-link/src/linktarget/LinkTargetActionsViewExtension.ts
linkUI.formView or linkUI.actionsView can be null here, if e.g. the imageBalloon was opened and closed here. Then, the linkUI view would be null and the visibleView is null as well when closing a balloon, leading to an error.
=> VisibleView null check added

packages/ckeditor5-coremedia-richtext/src/index-doc.ts, packages/ckeditor5-coremedia-richtext/src/integrations/index-doc.ts, packages/ckeditor5-link-common/README.md, packages/ckeditor5-link-common/src/index-doc.ts
Repairs appearance in GitHub pages regarding rendered API documentation.
=> docs(link): Fixes Documentation Issues

app/src/inputExampleContents.ts, packages/ckeditor5-coremedia-content/package.json, packages/ckeditor5-coremedia-content/src/OpenInTab.ts, packages/ckeditor5-coremedia-content/src/commands/OpenInTabCommand.ts, packages/ckeditor5-coremedia-content/src/index-doc.ts, packages/ckeditor5-coremedia-content/src/index.ts, packages/ckeditor5-coremedia-images/src/ContentImageEditingPlugin.ts, packages/ckeditor5-coremedia-images/src/augmentation.ts, packages/ckeditor5-coremedia-images/src/contentImageOpenInTab/ContentImageOpenInTabUI.ts, packages/ckeditor5-coremedia-images/src/contentImageOpenInTab/OpenImageInTabCommand.ts, packages/ckeditor5-coremedia-images/src/contentImageOpenInTab/index-doc.ts, packages/ckeditor5-coremedia-images/src/index.ts, packages/ckeditor5-coremedia-link/src/augmentation.ts, packages/ckeditor5-coremedia-link/src/contentlink/ContentLinks.ts, packages/ckeditor5-coremedia-link/src/contentlink/OpenContentInTabCommand.ts, packages/ckeditor5-coremedia-link/src/contentlink/index-doc.ts, packages/ckeditor5-coremedia-link/src/contentlink/ui/ContentLinkActionsViewExtension.ts, packages/ckeditor5-coremedia-link/src/contentlink/ui/ContentLinkViewFactory.ts, packages/ckeditor5-coremedia-link/src/index.ts, packages/ckeditor5-coremedia-studio-integration-mock/src/content/MockWorkAreaService.ts, packages/ckeditor5-coremedia-studio-integration-mock/src/content/PredefinedMockContents.ts, packages/ckeditor5-coremedia-studio-integration/src/content/studioservices/WorkAreaService.ts, pnpm-lock.yaml
> **Merge #145 first!**
>
> This is a rewrite of #146, as the original PR highly collides with changes for CKE5 37.x. When merged, change the base to `main`.
Given you moved the caret via cursor keys into a link-selection, and you opened the link balloon via Ctrl+K, you may have observed, that opening the link via mouse click failed.
The reason were improper updates of the enabled state of the corresponding command.
The fix mostly consists of refactoring to align detection of related model elements with corresponding features for images and links, as they ship with CKEditor 5. For the central issue, we completely disabled tracking the enabled state for now, as it was for no gain: The UI did not and does not represent a disabled state for unreadable or not existing referenced contents. As …
=> Content-Link: Fixes Mixed Keyboard/Mouse Access to Opening Content Links (Rewrite for CKE5 37.x)

.github/release.yml
This file applies some pattern to our release notes. It specifies parts, that are automatically generated. Note, though, that sections like required _Compatibility Matrix_ are not generated, as the configuration options are rather limited here.
See-also: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
=> feat(github): Automated Release Notes

packages/ckeditor5-coremedia-link/src/augmentation.ts, packages/ckeditor5-coremedia-link/src/contentlink/ContentLinks.ts, packages/ckeditor5-coremedia-link/src/contentlink/OpenContentInTabCommand.ts, packages/ckeditor5-coremedia-link/src/contentlink/ui/ContentLinkActionsViewExtension.ts, packages/ckeditor5-coremedia-link/src/contentlink/ui/ContentLinkViewFactory.ts
`CommandsMap` for command `openContentInTab` erroneously referenced to the command as `openLinkInTab`. This has been fixed.
Along with that, enhanced debugging for execution of that command, which may be helpful, if `openInTab` fails when invoked in context of CoreMedia Studio via its `WorkAreaService`.
=> fix(link): Augmentation in CommandsMap wrong for OpenContentInTab

packages/ckeditor5-coremedia-link/src/contentlink/ContentLinks.ts
In CoreMedia Studio, balloons must be hidden manually to disappear when the active Studio tab changes. In this case, no mouse click, that would usually close the balloon, appears. This was previously fixed in the link balloon init method, that got called as soon as a link balloon was opened. However, we also need this fix when using the image balloon (open image in tab). This use case did not work anymore, after refactoring the workspace as part of a CKEditor upgrade.
We now listen to active tab changes in the link plugin as soon as the link plugin is initialized and don't wait for the balloon to be opened.
=> fix(hide balloon): Hide balloon on active tab change

app/src/ckeditor.ts, packages/ckeditor5-coremedia-link/__tests__/linktarget/config/LinkDefaultTargetsConfig.test.ts, packages/ckeditor5-coremedia-link/src/augmentation.ts, packages/ckeditor5-coremedia-link/src/linktarget/LinkTargetModelView.ts, packages/ckeditor5-coremedia-link/src/linktarget/README.md, packages/ckeditor5-coremedia-link/src/linktarget/config/DefaultTargetTypeFilters.ts, packages/ckeditor5-coremedia-link/src/linktarget/config/LinkTargetConfig.ts, packages/ckeditor5-coremedia-link/src/linktarget/config/LinkTargetDefaultRuleDefinition.ts, packages/ckeditor5-coremedia-link/src/linktarget/config/index-doc.ts
Since it is a common use-case, we provide a configuration for the default target of links.
The default target can be set, depending on the url of the link, or by differentiating between external links and links to content items.
=> Feature(link): Default target configuration

packages/ckeditor5-coremedia-link/src/contentlink/ui/ContentLinkActionsViewExtension.ts, packages/ckeditor5-coremedia-studio-integration/src/index.ts
Exporting the UriPath via default named exports leads to a warning during a build. 
The better way of importing/exporting types is to use the "type" prefix to ensure the import is only present in TypeScript files.
=> Fixes export 'UriPath' ... was not found in './content/UriPath' warning during build

packages/ckeditor5-coremedia-richtext-support/src/augmentation.ts, packages/ckeditor5-coremedia-richtext/src/augmentation.ts, packages/ckeditor5-font-mapper/src/augmentation.ts
The EditorConfig type extensions in some of our augmentation files were marked as mandatory. This is false. TypeScript would complain about insufficient configs if these plugins were not configured. (Which is totally fine) Therefore, these config extensions are now marked as optional.
Cherry-picked from BBCode Branch, kudos to @pkliesch.
=> fix: Fix false mandatory EditorConfig Types

packages/ckeditor5-common/package.json, packages/ckeditor5-common/src/AdvancedTypes.ts, packages/ckeditor5-common/src/index.ts, packages/ckeditor5-coremedia-richtext/__tests__/rules/AnchorElements.test.ts, packages/ckeditor5-coremedia-richtext/src/index.ts, packages/ckeditor5-coremedia-richtext/src/rules/AnchorElements.ts, packages/ckeditor5-coremedia-richtext/src/rules/XLink.ts, packages/ckeditor5-dom-converter/package.json, packages/ckeditor5-dom-converter/src/Rule.ts, packages/ckeditor5-dom-support/src/Attrs.ts, packages/ckeditor5-dom-support/src/index.ts, pnpm-lock.yaml
`xlink:show` and `xlink:role` have a combined semantic within CoreMedia Rich Text 1.0. If `xlink:show` is set to `"other"`, it is expected, that `xlink:role` contains a non-empty value, that is typically rendered as `target` attribute when delivering the Rich Text on websites. We do the same in the view layers of CKEditor 5.
For any other valid value of `xlink:show` the behavior for any non-empty value of `xlink:role` is not specified. The default implementation of the Rich Text data-processor assumes this to be an artificial/unexpected state and tries to preserve it, by encoding it into the `target` attribute to preserve its state.
Having this, the following represents an _artificial `xlink:role`:_
```xml
<?xml version="1.0" encoding="utf-8"?>
<div …
```
=> feat: Handle Artificial xlink:role values (Opt-In)

packages/ckeditor5-core-common/package.json
Missed updating peerDependencies to 39.0.2 in ckeditor5-core-common.
=> fix(core-common): Fix peerDependencies

.github/workflows/pre-release.yml, .github/workflows/release.yml, package.json, pnpm-lock.yaml, scripts/validate-peers.mjs
Adds the opt-in to validate `peerDependencies` if they match the actual dependencies.
This check works best for fixed versions, which we may want to introduce anyway, as it aligns with the CKEditor 5 packages and as it is a CKEditor 5 requirement that a deliverable only refers to one CKEditor 5 version for all used packages.
* Change one of the `peerDependencies` for a CKEditor 5 package to `39.0.0` (we are at `39.0.2`, currently).
* Run `pnpm script:validate-peers`
Regarding the "script" prefix: This helps to prevent possibly collisions with internal `pnpm` actions. While not relevant for `validate-peers`, we had issues with `version`, why we had to introduce some name-clash resolution and decided for `script:version`. It seems to be a good idea, to continue using this namespace.
For …
=> Validate peer dependencies

packages/ckeditor5-coremedia-link/src/linktarget/LinkTargetModelView.ts, packages/ckeditor5-coremedia-link/src/linktarget/config/LinkTargetConfig.ts
The post-fixer for links is also invoked when removing links. In this case, the calculated link is `null`.
The previous code struggled, because brute-force casting to `string` instead of doing some type-checking.
Also, the previous code was not robust, when any of the filters got an issue. As such filters may be part of the configuration, we should be robust on invocation and handle it in some predictable way.
The fix is two-fold:
* We do not invoke the filter on link removal anymore.
* We added a robustness layer for custom filters, if they fail with exception. Decision is to ignore the corresponding filter, which is, that on failure, no default target will be selected.
=> fix(link): Harden Default Target Calculation

.github/workflows/build.yml, .github/workflows/get-version.yml, .github/workflows/pre-release-gc.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml
Using Node.js 20, we now get warnings such as:
```
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20:
actions/checkout@v3, actions/setup-node@v3.
For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
To address this, an update of the corresponding actions is required. PNPM, though, does not provide a solution yet.
=> Deal with GitHub Actions Node.js 16 Deprecations

pnpm-lock.yaml
GHSA-3h5v-q93c-6h6q, CVE-2024-37890 - ws affected by a DoS when handling a request with many HTTP headers
=> fix CKE-72. Update ws to 8.18.0

app/src/editors/richtext.ts, packages/ckeditor5-coremedia-richtext/README.md, packages/ckeditor5-coremedia-richtext/__tests__/rules/FixedAttributes.test.ts, packages/ckeditor5-coremedia-richtext/__tests__/sanitation/RichTextSanitizer.test.ts, packages/ckeditor5-coremedia-richtext/src/index.ts, packages/ckeditor5-coremedia-richtext/src/rules/FixedAttributes.ts, packages/ckeditor5-coremedia-richtext/src/rules/index-doc.ts, packages/ckeditor5-coremedia-richtext/src/sanitation/ElementConfig.ts
`RichTextSanitizer` used to remove an attribute if it has a fixed valid value as it seemed obsolete. E.g. `<img xlink:show= "embed">`. Now such an attribute is kept, stored and therefore can be used in the presentation layer. 
To restore the old behavior which removes such an attribute use the provided data processing rule `stripFixedAttributes`.
=> CKE-67 Keep an attribute with valid fixed value

packages/ckeditor5-coremedia-richtext/src/rules/ImageElements.ts, packages/ckeditor5-coremedia-richtext/src/rules/XLink.ts
Adds TSdoc and a new feature to `setXLinkAttributes` in `XLink` tooling.
`allowEmpty` is required to be `true` if, for example, you need to explicitly set a value for a required attribute and it must not be skipped (such as an `<a>` which aways requires `xlink:href` to comply with CoreMedia Rich Text DTD 1.0).
To not break existing usages, `allowEmpty` must default to `false`.
**Decide on breaking change:**
As additional part of this PR, also decided to align the behavior of `setXLinkDataSetEntries`
with `setXLinkAttributes`, thus, to (by default) drop attributes with empty values. While this
is aligned with the DevNote that existed before, this has to be considered a **breaking change**.
Usages that rely on "empty values" to be accepted, need to explicitly add `allowEmpty = true` to the …
=> feat(coremedia-richtext): TSdoc and allowEmpty (XLink)
